"""Initial migration

Revision ID: d5c1905d34b9
Revises: c3d91aa428ac
Create Date: 2025-12-07 22:33:03.088084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5c1905d34b9'
down_revision = 'c3d91aa428ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

